platform :ios, '8.0'

target 'ProjectWithTabBarMVC' do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 1.0.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager', '~> 4.0.8'
pod 'MJRefresh', '~> 3.1.12'
pod 'LTNavigationBar', '~> 2.1.9'
pod 'MJExtension', '~> 3.0.13'
end
